---
- name: "Define openresty_user."
  ansible.builtin.set_fact:
    openresty_user: "{{ __openresty_user }}"
  when: openresty_user is not defined

- name: "Create log directory."
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0640
  with_items:
    - /var/log/openresty

- name: Install tasks
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Secure config
  ansible.builtin.import_tasks: secure.yml

- name: Vhost config
  ansible.builtin.import_tasks: vhosts.yml

- name: "Copy openresty configuration."
  ansible.builtin.template:
    src: "{{ openresty_conf_template }}"
    dest: "{{ openresty_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0640
  notify: "Reload openresty"

- name: "Ensure openresty service is running as configured."
  ansible.builtin.service:
    name: openresty
    state: "{{ openresty_service_state }}"
    enabled: "{{ openresty_service_enabled }}"

- name: Add logrotate file
  ansible.builtin.copy:
    mode: 0640
    dest: /etc/logrotate.d/openresty
    content: |
      /var/log/openresty/*.log {
          #rotate the logfile(s) daily
          daily
          # If log file is missing, go on to next one without issuing an error msg
          missingok
          # Save logfiles for the last 10 days
          rotate 14
          # Old versions of log files are compressed with gzip
          compress
          # Postpone compression of the previous log file to the next rotation cycle
          delaycompress
          # Do not rotate the log if it is empty
          notifempty
          create 0640 www-data adm
          sharedscripts
          # adds extension like YYYYMMDD instead of simply adding a number
          #dateext
          #after logfile is rotated and nginx.pid exists, send the USR1 signal
          postrotate
              for inode in $(stat -c %i $1); do
                  /bin/rm /var/spool/rsyslog/imfile-state:$inode 2>/dev/null || true
              done
              #[ ! -f /var/run/nginx.pid  ] || kill -USR1 `cat /var/run/nginx.pid`
              service openresty reload >/dev/null 2>&1
          endscript
      }
