---
- name: "Create conf.d directory."
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0640
  with_items:
    - "{{ openresty_conf_path }}"

- name: "Create additional configuration."
  ansible.builtin.template:
    src: "hardening.conf.j2"
    dest: "{{ openresty_conf_path }}/90.hardening.conf"
    owner: "root"
    group: "root"
    mode: 0640
  notify: restart openresty

- name: "Config should not be worldwide read or writeable."
  ansible.builtin.file:
    path: "{{ openresty_conf_path }}"
    mode: 0640
    owner: "root"
    group: "root"
    recurse: true

- name: "Generate dh group."
  ansible.builtin.command: "openssl dhparam -out /etc/openresty/dh{{ openresty_dh_size }}.pem {{ openresty_dh_size }}"
  args:
    creates: "/etc/openresty/dh{{ openresty_dh_size }}.pem"
  notify: restart openresty
