---
- name: "Install requierement."
  ansible.builtin.package:
    name: ['gnupg', 'ca-certificates']
    state: present

- name: "Import the openresty apt key."
  ansible.builtin.apt_key:
    url: https://openresty.org/package/pubkey.gpg
    state: present

- name: "Add openresty repository."
  ansible.builtin.apt_repository:
    repo: deb http://openresty.org/package/debian buster openresty
    state: present

    #- name: "Update apt cache."
    #  apt: update_cache=yes cache_valid_time=86400
    #  changed_when: false

- name: "Ensure openresty is installed."
  ansible.builtin.package:
    name: "{{ openresty_package_name }}"
    state: present

- name: "Get list of installed lua plugins."
  ansible.builtin.command: opm list | awk '{print $1}'
  register: openresty_plugins_list
  changed_when: false

- name: "Install extra lua plugins."
  ansible.builtin.command: opm install {{ item }}
  with_items:
    - "{{ openresty_install_plugins }}"
  when: "item not in openresty_plugins_list.stdout"
  notify:
