---
- name: restart openresty
  service: name=openresty state=restarted

- name: validate openresty configuration
  command: openresty -t -c /usr/local/openresty/nginx/conf/nginx.conf
  changed_when: false

- name: reload openresty
  service: name=openresty state=reloaded
