---
- name: restart openresty
  ansible.builtin.service: name=openresty state=restarted

- name: validate openresty configuration
  ansible.builtin.command: openresty -t -c /usr/local/openresty/nginx/conf/nginx.conf
  changed_when: false

- name: reload openresty
  ansible.builtin.service: name=openresty state=reloaded
